cmake_minimum_required(VERSION 4.3)
project(cpp_course_lab_works)

set(CMAKE_CXX_STANDARD 20)

#lab2
add_executable(exercise1 lab2/functions/exercise1.cpp)
add_executable(exercise2 lab2/functions/exercise2.cpp)
add_executable(lab2-character-sequence-exercise1 lab2/character-sequence/lab2-character-sequence-exercise1.cpp)

#lab4
add_executable(lab4-exercise1 lab4/pointers-addresses-references/lab4-exercise1.cpp)
add_executable(lab4-exercise2 lab4/pointers-addresses-references/lab4-exercise2.cpp)
add_executable(lab4-exercise3 lab4/pointers-addresses-references/lab4-exercise3.cpp)
add_executable(lab4-exercise4 lab4/pointers-addresses-references/lab4-exercise4.cpp)



